// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    { type: "autogenerated", dirName: "home" },
    {
      type: 'link',
      label: 'Paima Game Templates',
      href: 'https://github.com/PaimaStudios/paima-game-templates',
    },
    {
      type: 'link',
      label: 'EffectStream Github',
      href: 'https://github.com/effectstream/effectstream/',
    },
  ],
};

module.exports = sidebars;
