// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    { type: "autogenerated", dirName: "home" },
    // The generated "Templates" category above documents all of these; this
    // link is the shortcut to the source directory, so it is labelled to be
    // distinguishable from that category rather than competing with it.
    {
      type: 'link',
      label: 'Templates on GitHub',
      href: 'https://github.com/effectstream/effectstream/tree/main/templates',
    },
    {
      type: 'link',
      label: 'EffectStream Github',
      href: 'https://github.com/effectstream/effectstream/',
    },
  ],
};

module.exports = sidebars;
