const examples = [
  { "name": "Abu Simbel Temples", "country": "Egypt", "city": "Aswan" },
  { "name": "Acropolis", "country": "Greece", "city": "Athens" },
  {
    "name": "Alcatraz Island",
    "country": "United States",
    "city": "San Francisco",
  },
  { "name": "Alhambra", "country": "Spain", "city": "Granada" },
  { "name": "Angkor Wat", "country": "Cambodia", "city": "Siem Reap" },
  { "name": "Atomium", "country": "Belgium", "city": "Brussels" },
  { "name": "Bagan Temples", "country": "Myanmar", "city": "Bagan" },
  {
    "name": "Band-e Amir National Park",
    "country": "Afghanistan",
    "city": "Bamyan",
  },
  { "name": "Banff National Park", "country": "Canada", "city": "Banff" },
  { "name": "Basilica di San Marco", "country": "Italy", "city": "Venice" },
  { "name": "Berat Castle", "country": "Albania", "city": "Berat" },
  { "name": "Big Ben", "country": "United Kingdom", "city": "London" },
  { "name": "Blue Lagoon", "country": "Iceland", "city": "Grindavik" },
  { "name": "Blue Mosque", "country": "Turkey", "city": "Istanbul" },
  { "name": "Bosporus Bridge", "country": "Turkey", "city": "Istanbul" },
  { "name": "Bosra Amphitheatre", "country": "Syria", "city": "Bosra" },
  { "name": "Bran Castle", "country": "Romania", "city": "Bran" },
  { "name": "Brandenburg Gate", "country": "Germany", "city": "Berlin" },
  {
    "name": "Buckingham Palace",
    "country": "United Kingdom",
    "city": "London",
  },
  {
    "name": "Buckingham Palace",
    "country": "United Kingdom",
    "city": "London",
  },
  {
    "name": "Burj Khalifa",
    "country": "United Arab Emirates",
    "city": "Dubai",
  },
  {
    "name": "Butrint Archaeological Site",
    "country": "Albania",
    "city": "Butrint",
  },
  {
    "name": "Capitol Hill",
    "country": "United States",
    "city": "Washington D.C.",
  },
  { "name": "Cappadocia", "country": "Turkey", "city": "Goreme" },
  { "name": "Cappadocia", "country": "Turkey", "city": "Göreme" },
  { "name": "Casbah of Algiers", "country": "Algeria", "city": "Algiers" },
  { "name": "Castel Sant'Angelo", "country": "Italy", "city": "Rome" },
  { "name": "Central Park", "country": "United States", "city": "New York" },
  { "name": "Champs-Élysées", "country": "France", "city": "Paris" },
  { "name": "Chichen Itza", "country": "Mexico", "city": "Yucatan" },
  { "name": "Christ Church Cathedral", "country": "Ireland", "city": "Dublin" },
  { "name": "Christ Church", "country": "New Zealand", "city": "Christchurch" },
  {
    "name": "Christ the Redeemer",
    "country": "Brazil",
    "city": "Rio de Janeiro",
  },
  { "name": "CN Tower", "country": "Canada", "city": "Toronto" },
  { "name": "Cologne Cathedral", "country": "Germany", "city": "Cologne" },
  { "name": "Colosseum", "country": "Italy", "city": "Rome" },
  { "name": "Copacabana Beach", "country": "Brazil", "city": "Rio de Janeiro" },
  { "name": "Crac des Chevaliers", "country": "Syria", "city": "Homs" },
  { "name": "Duomo di Milano", "country": "Italy", "city": "Milan" },
  { "name": "Easter Island Statues", "country": "Chile", "city": "Hanga Roa" },
  {
    "name": "Edinburgh Castle",
    "country": "United Kingdom",
    "city": "Edinburgh",
  },
  { "name": "Eiffel Tower", "country": "France", "city": "Paris" },
  {
    "name": "Empire State Building",
    "country": "United States",
    "city": "New York",
  },
  { "name": "Fisherman's Bastion", "country": "Hungary", "city": "Budapest" },
  { "name": "Flame Towers", "country": "Azerbaijan", "city": "Baku" },
  { "name": "Flame Towers", "country": "Azerbaijan", "city": "Baku" },
  { "name": "Forbidden City", "country": "China", "city": "Beijing" },
  { "name": "Fortress of São Miguel", "country": "Angola", "city": "Luanda" },
  { "name": "Fushimi Inari-taisha", "country": "Japan", "city": "Kyoto" },
  { "name": "Geghard Monastery", "country": "Armenia", "city": "Kotayk" },
  {
    "name": "Glacier National Park",
    "country": "United States",
    "city": "Montana",
  },
  {
    "name": "Golden Gate Bridge",
    "country": "United States",
    "city": "San Francisco",
  },
  { "name": "Golden Pavilion", "country": "Japan", "city": "Kyoto" },
  { "name": "Grand Bazaar", "country": "Turkey", "city": "Istanbul" },
  { "name": "Grand Canyon", "country": "United States", "city": "Arizona" },
  { "name": "Grand Place", "country": "Belgium", "city": "Brussels" },
  {
    "name": "Great Barrier Reef",
    "country": "Australia",
    "city": "Queensland",
  },
  { "name": "Great Wall of China", "country": "China", "city": "Beijing" },
  { "name": "Guggenheim Museum", "country": "Spain", "city": "Bilbao" },
  { "name": "Hagia Sophia", "country": "Turkey", "city": "Istanbul" },
  { "name": "Harbour Bridge", "country": "Australia", "city": "Sydney" },
  {
    "name": "Hermitage Museum",
    "country": "Russia",
    "city": "Saint Petersburg",
  },
  { "name": "Hermitage Museum", "country": "Russia", "city": "St. Petersburg" },
  { "name": "Hofburg Palace", "country": "Austria", "city": "Vienna" },
  {
    "name": "Hollywood Sign",
    "country": "United States",
    "city": "Los Angeles",
  },
  {
    "name": "Iguaçu National Park",
    "country": "Brazil",
    "city": "Foz do Iguaçu",
  },
  { "name": "Iguazu Falls", "country": "Argentina", "city": "Puerto Iguazú" },
  { "name": "Khor Virap Monastery", "country": "Armenia", "city": "Ararat" },
  { "name": "Kremlin", "country": "Russia", "city": "Moscow" },
  { "name": "La Boca", "country": "Argentina", "city": "Buenos Aires" },
  { "name": "La Sagrada Familia", "country": "Spain", "city": "Barcelona" },
  { "name": "Lake Louise", "country": "Canada", "city": "Banff" },
  { "name": "Lascaux Caves", "country": "France", "city": "Montignac" },
  { "name": "Leaning Tower of Pisa", "country": "Italy", "city": "Pisa" },
  { "name": "Louvre Museum", "country": "France", "city": "Paris" },
  { "name": "Machu Picchu", "country": "Peru", "city": "Cusco" },
  { "name": "Maiden Tower", "country": "Azerbaijan", "city": "Baku" },
  { "name": "Matterhorn", "country": "Switzerland", "city": "Zermatt" },
  { "name": "Mecca Masjid", "country": "Saudi Arabia", "city": "Mecca" },
  { "name": "Minaret of Jam", "country": "Afghanistan", "city": "Shahrak" },
  { "name": "Moai Statues", "country": "Chile", "city": "Easter Island" },
  { "name": "Moai", "country": "Chile", "city": "Easter Island" },
  { "name": "Mole Antonelliana", "country": "Italy", "city": "Turin" },
  { "name": "Mont Saint Michel", "country": "France", "city": "Normandy" },
  { "name": "Mont Saint-Michel", "country": "France", "city": "Normandy" },
  { "name": "Mount Everest", "country": "Nepal", "city": "Solukhumbu" },
  { "name": "Mount Fuji", "country": "Japan", "city": "Fujinomiya" },
  { "name": "Mount Rushmore", "country": "United States", "city": "Keystone" },
  { "name": "Museo del Prado", "country": "Spain", "city": "Madrid" },
  { "name": "National Palace", "country": "Mexico", "city": "Mexico City" },
  { "name": "Navy Pier", "country": "United States", "city": "Chicago" },
  { "name": "Nazca Lines", "country": "Peru", "city": "Nazca" },
  {
    "name": "Neuschwanstein Castle",
    "country": "Germany",
    "city": "Schwangau",
  },
  { "name": "Notre Dame d'Afrique", "country": "Algeria", "city": "Algiers" },
  { "name": "Notre Dame de Paris", "country": "France", "city": "Paris" },
  { "name": "Notre-Dame Cathedral", "country": "France", "city": "Paris" },
  { "name": "Obelisco", "country": "Argentina", "city": "Buenos Aires" },
  { "name": "Old Trafford", "country": "United Kingdom", "city": "Manchester" },
  { "name": "Olympic Stadium", "country": "Canada", "city": "Montreal" },
  { "name": "Opera House", "country": "Czech Republic", "city": "Prague" },
  {
    "name": "Palace of the Parliament",
    "country": "Romania",
    "city": "Bucharest",
  },
  { "name": "Palace of Versailles", "country": "France", "city": "Versailles" },
  { "name": "Pamukkale", "country": "Turkey", "city": "Pamukkale" },
  { "name": "Pena Palace", "country": "Portugal", "city": "Sintra" },
  {
    "name": "Perito Moreno Glacier",
    "country": "Argentina",
    "city": "Santa Cruz",
  },
  { "name": "Petra", "country": "Jordan", "city": "Petra" },
  { "name": "Petronas Towers", "country": "Malaysia", "city": "Kuala Lumpur" },
  {
    "name": "Pike Place Market",
    "country": "United States",
    "city": "Seattle",
  },
  { "name": "Pompeii", "country": "Italy", "city": "Pompeii" },
  { "name": "Potala Palace", "country": "China", "city": "Lhasa" },
  { "name": "Prague Castle", "country": "Czech Republic", "city": "Prague" },
  { "name": "Pyramids of Giza", "country": "Egypt", "city": "Giza" },
  { "name": "Qutub Minar", "country": "India", "city": "Delhi" },
  { "name": "Red Square", "country": "Russia", "city": "Moscow" },
  { "name": "Rijksmuseum", "country": "Netherlands", "city": "Amsterdam" },
  { "name": "Robben Island", "country": "South Africa", "city": "Cape Town" },
  { "name": "Sagrada Familia", "country": "Spain", "city": "Barcelona" },
  {
    "name": "Saint Peter's Basilica",
    "country": "Vatican City",
    "city": "Vatican City",
  },
  { "name": "Salt Cathedral", "country": "Colombia", "city": "Zipaquira" },
  { "name": "Salzburg Fortress", "country": "Austria", "city": "Salzburg" },
  {
    "name": "Sant Joan de Caselles Church",
    "country": "Andorra",
    "city": "Canillo",
  },
  { "name": "Santorini", "country": "Greece", "city": "Santorini" },
  { "name": "Schönbrunn Palace", "country": "Austria", "city": "Vienna" },
  {
    "name": "Sheikh Zayed Grand Mosque",
    "country": "United Arab Emirates",
    "city": "Abu Dhabi",
  },
  { "name": "Shwedagon Pagoda", "country": "Myanmar", "city": "Yangon" },
  {
    "name": "Sistine Chapel",
    "country": "Vatican City",
    "city": "Vatican City",
  },
  { "name": "Space Needle", "country": "United States", "city": "Seattle" },
  { "name": "Sphinx", "country": "Egypt", "city": "Giza" },
  { "name": "St. Basil's Cathedral", "country": "Russia", "city": "Moscow" },
  {
    "name": "Stari Most",
    "country": "Bosnia and Herzegovina",
    "city": "Mostar",
  },
  {
    "name": "Statue of Liberty",
    "country": "United States",
    "city": "New York",
  },
  { "name": "Stonehenge", "country": "United Kingdom", "city": "Amesbury" },
  {
    "name": "Sugarloaf Mountain",
    "country": "Brazil",
    "city": "Rio de Janeiro",
  },
  { "name": "Sydney Opera House", "country": "Australia", "city": "Sydney" },
  { "name": "Table Mountain", "country": "South Africa", "city": "Cape Town" },
  { "name": "Taj Mahal", "country": "India", "city": "Agra" },
  { "name": "Tassili n'Ajjer", "country": "Algeria", "city": "Djanet" },
  { "name": "Terracotta Army", "country": "China", "city": "Xi'an" },
  { "name": "The Louvre", "country": "France", "city": "Paris" },
  { "name": "The Shard", "country": "United Kingdom", "city": "London" },
  { "name": "Three Gorges Dam", "country": "China", "city": "Yichang" },
  { "name": "Tokyo Tower", "country": "Japan", "city": "Tokyo" },
  { "name": "Torre del Oro", "country": "Spain", "city": "Seville" },
  {
    "name": "Torre Latinoamericana",
    "country": "Mexico",
    "city": "Mexico City",
  },
  { "name": "Tower Bridge", "country": "United Kingdom", "city": "London" },
  { "name": "Tower of London", "country": "United Kingdom", "city": "London" },
  { "name": "Tower of Pisa", "country": "Italy", "city": "Pisa" },
  { "name": "Tulum Ruins", "country": "Mexico", "city": "Tulum" },
  { "name": "Uffizi Gallery", "country": "Italy", "city": "Florence" },
  { "name": "Uluru", "country": "Australia", "city": "Northern Territory" },
  { "name": "Umayyad Mosque", "country": "Syria", "city": "Damascus" },
  {
    "name": "Universal Studios",
    "country": "United States",
    "city": "Orlando",
  },
  { "name": "Valley of the Kings", "country": "Egypt", "city": "Luxor" },
  { "name": "Venice Grand Canal", "country": "Italy", "city": "Venice" },
  { "name": "Versailles Palace", "country": "France", "city": "Versailles" },
  { "name": "Victoria Falls", "country": "Zambia", "city": "Livingstone" },
  { "name": "Wawel Castle", "country": "Poland", "city": "Krakow" },
];

// Initial sample NFT data for the wallet demo
export const initialNFTSamples = [
  {
    "streetAddress": "1600 Pennsylvania Ave NW",
    "zipCode": "20500",
    "city": "Washington",
    "state": "DC",
    "nearbyLandmark": "The White House",
    "cityFoundingDate": "1790-07-16",
  },
  {
    "streetAddress": "4059 Mt Lee Dr",
    "zipCode": "90068",
    "city": "Los Angeles",
    "state": "CA",
    "nearbyLandmark": "Hollywood Sign",
    "cityFoundingDate": "1781-09-04",
  },
  {
    "streetAddress": "1 Infinite Loop",
    "zipCode": "95014",
    "city": "Cupertino",
    "state": "CA",
    "nearbyLandmark": "Apple Park",
    "cityFoundingDate": "1955-10-10",
  },
  {
    "streetAddress": "350 5th Ave",
    "zipCode": "10118",
    "city": "New York",
    "state": "NY",
    "nearbyLandmark": "Empire State Building",
    "cityFoundingDate": "1624-01-01",
  },
  {
    "streetAddress": "221B Baker St",
    "zipCode": "02116",
    "city": "Boston",
    "state": "MA",
    "nearbyLandmark": "Sherlock Holmes Museum",
    "cityFoundingDate": "1630-09-07",
  },
];

export default examples;
