// Browser-side Midnight contract client for the OfferFiles contract.
// Modeled on e2e/wallets-ui/client/src/contracts/counter.ts — the same
// provider stack, with OfferFilesContract in place of Counter and the demo's
// three circuits (mint_shielded, mint_unshielded, incrementNoun) exposed.

import type { ConnectedAPI } from '@midnight-ntwrk/dapp-connector-api';
import type { ContractWallet } from './contractWallet';
import {
  findDeployedContract,
  type FoundContract,
} from '@midnight-ntwrk/midnight-js-contracts';
import { httpClientProofProvider } from '@midnight-ntwrk/midnight-js-http-client-proof-provider';
import { indexerPublicDataProvider } from '@midnight-ntwrk/midnight-js-indexer-public-data-provider';
import { FetchZkConfigProvider } from '@midnight-ntwrk/midnight-js-fetch-zk-config-provider';
import { levelPrivateStateProvider } from '@midnight-ntwrk/midnight-js-level-private-state-provider';
import {
  type CoinPublicKey,
  type EncPublicKey,
  type FinalizedTransaction,
  Transaction as LedgerV8Transaction,
  type TransactionId,
} from '@midnight-ntwrk/ledger-v8';
import {
  type MidnightProvider,
  type MidnightProviders,
  type UnboundTransaction,
  type WalletProvider,
} from '@midnight-ntwrk/midnight-js-types';
import { CompiledContract } from '@midnight-ntwrk/compact-js';
import { type NetworkId, setNetworkId } from '@midnight-ntwrk/midnight-js-network-id';
// Still needed by the Lace-only settle path below; the mint path's key
// normalization now lives behind ContractWallet.
import { parseCoinPublicKeyToHex } from '@midnight-ntwrk/midnight-js-utils';

// Build output of src/contract/offer-files.compact — generated by
// `bun run build:contract` (run automatically via predev/prebuild) and verified
// against src/contract/manifest.json. Not to be confused with `OfferFiles`
// below: that is the MIP-0005 codec, unrelated to this contract despite the
// name.
import * as OfferFilesContract from '../contract/managed/contract/index.js';
import { API_BASE } from '../config';
import { submitToBatcher } from './api';
import {
  chooseLaceBalancing,
  decodeMakerOffers,
  mergeMakerOffersToBytes,
} from './offerBatch';
import { dlog, timed } from '../debug';

export interface MidnightBrowserConfig {
  contractAddress: string;
  indexerUri: string;
  indexerWsUri: string;
  proofServerUri: string;
  networkId: string;
}

export type OfferFilesCircuits = 'mint_shielded' | 'mint_unshielded' | 'incrementNoun';
export const OFFER_FILES_PRIVATE_STATE_ID = 'offerFilesPrivateState';
export type OfferFilesProviders = MidnightProviders<
  OfferFilesCircuits,
  typeof OFFER_FILES_PRIVATE_STATE_ID,
  {}
>;
export type FoundOfferFilesContract = FoundContract<OfferFilesContract.Contract>;

export interface ConnectedOfferFilesContract {
  readonly contract: FoundOfferFilesContract;
  readonly providers: OfferFilesProviders;
  readonly compiledContract: any;
  readonly config: MidnightBrowserConfig;
}

const toHex = (data: Uint8Array): string =>
  Array.from(data, (b) => b.toString(16).padStart(2, '0')).join('');

const fromHex = (hex: string): Uint8Array => {
  const clean = hex.startsWith('0x') ? hex.slice(2) : hex;
  const out = new Uint8Array(clean.length / 2);
  for (let i = 0; i < out.length; i++) {
    out[i] = parseInt(clean.slice(i * 2, i * 2 + 2), 16);
  }
  return out;
};

function createWalletAndMidnightProvider(
  wallet: ContractWallet,
  coinPublicKey: CoinPublicKey,
  encryptionPublicKey: EncPublicKey,
): WalletProvider & MidnightProvider {
  return {
    getCoinPublicKey(): CoinPublicKey {
      return coinPublicKey;
    },
    getEncryptionPublicKey(): EncPublicKey {
      return encryptionPublicKey;
    },
    async balanceTx(tx: UnboundTransaction, ttl?: Date): Promise<FinalizedTransaction> {
      // The wallet seals the tx without contributing Dust; the batcher balances
      // fees and submits, so the user's wallet pays none. Both wallets express
      // that differently (Lace: payFees:false — JS wallet: omit 'dust' from
      // tokenKindsToBalance), which is why it lives behind ContractWallet.
      console.log(`[browserContract] balanceTx via ${wallet.label}`);
      try {
        return await wallet.balanceUnbound(tx, ttl);
      } catch (e: any) {
        console.error('[browserContract] balanceTx: wallet rejected', {
          wallet: wallet.kind,
          name: e?.name,
          message: e?.message,
          raw: e,
        });
        throw e instanceof Error
          ? e
          : new Error(`balanceTx failed: ${String(e)}`, { cause: e });
      }
    },
    async submitTx(tx: FinalizedTransaction): Promise<TransactionId> {
      const serializedHex = toHex(tx.serialize());
      // midnight-js polls the indexer by `identifier`, not by tx hash
      // (TX_ID_QUERY uses `offset: { identifier }`). Compute the identifier
      // from the finalized tx itself — the batcher only returns a hash, which
      // would never match and cause watchForTxData to hang.
      const identifiers = (tx as any).identifiers?.() as string[] | undefined;
      const localHash = (tx as any).transactionHash?.() as string | undefined;
      console.log('[browserContract] submitTx: routing to batcher', {
        localHash,
        identifiers,
      });
      try {
        await submitToBatcher(serializedHex, 'finalized', coinPublicKey as unknown as string);
        const identifier = identifiers?.[0];
        if (!identifier) {
          throw new Error('ledger tx returned no identifiers — cannot track finalization');
        }
        return identifier as TransactionId;
      } catch (e: any) {
        console.error('[browserContract] submitTx: batcher submit failed', {
          message: e?.message,
          raw: e,
        });
        throw new Error(
          `batcher submit failed: ${e?.message ?? JSON.stringify(e) ?? 'unknown'}`,
          { cause: e },
        );
      }
    },
  };
}

async function buildProviders(
  wallet: ContractWallet,
  config: MidnightBrowserConfig,
): Promise<OfferFilesProviders> {
  // Each wallet returns these in its own encoding — Lace in bech32m (parsed to
  // hex), the JS wallet already in hex. ContractWallet owns that difference;
  // what arrives here is always the hex ledger-v8 expects.
  const { coinPublicKeyHex, encPublicKeyHex } = await wallet.getShieldedKeys(config.networkId);

  // Diagnostic dump — the coin public key here is the recipient baked into the
  // mint output's coin commitment, AND the encryption ciphertext is keyed off
  // encPublicKeyHex. If either doesn't match what the wallet actually scans
  // for, the wallet will never claim the mint.
  console.log('[browserContract] keys for mint output recipient + ciphertext', {
    wallet: wallet.kind,
    networkId: config.networkId,
    coinPublicKeyHex,
    coinPublicKeyHexLen: coinPublicKeyHex.length,
    encPublicKeyHex,
    encPublicKeyHexLen: encPublicKeyHex.length,
  });

  const walletAndMidnightProvider = createWalletAndMidnightProvider(
    wallet,
    coinPublicKeyHex as unknown as CoinPublicKey,
    encPublicKeyHex as unknown as EncPublicKey,
  );

  // ZK assets are served by the backend (GET /keys/*, /zkir/* in the
  // zswap-offerfiles-kernel repo), not by this app's origin.
  //
  // safeFetch: force no-store (so a recompiled contract's keys are never
  // substituted by stale cache), and synthesize a 404 for any response whose
  // Content-Type starts with text/html (a misconfigured host's SPA fallback
  // would otherwise masquerade as key bytes — the provider only checks
  // `response.ok`). Missing-key lookups then throw inside sendRequest →
  // getKeyMaterial catches and returns undefined → the proof server falls
  // back to its own bundled keys for the built-in circuits.
  const safeFetch: typeof fetch = async (input, init) => {
    const res = await fetch(input as any, { ...(init ?? {}), cache: 'no-store' });
    const contentType = res.headers.get('content-type') ?? '';
    if (res.ok && contentType.toLowerCase().startsWith('text/html')) {
      return new Response(null, { status: 404, statusText: 'Not Found (HTML fallback)' });
    }
    return res;
  };
  const zkConfigProvider = new FetchZkConfigProvider<OfferFilesCircuits>(
    API_BASE,
    safeFetch.bind(window),
  );

  return {
    privateStateProvider: levelPrivateStateProvider({
      privateStoragePasswordProvider: async () => 'ZSWAP_DA_STORAGE_PASSWORD_16+',
      // Account-scope storage to the connected wallet so switching wallets
      // doesn't leak or collide private state across accounts. Use the hex
      // form so the storage key matches the canonical CoinPublicKey shape
      // and stays stable across any Lace bech32-prefix changes.
      accountId: coinPublicKeyHex,
    } as any),
    zkConfigProvider,
    proofProvider: httpClientProofProvider(config.proofServerUri, zkConfigProvider),
    publicDataProvider: indexerPublicDataProvider(config.indexerUri, config.indexerWsUri),
    walletProvider: walletAndMidnightProvider,
    midnightProvider: walletAndMidnightProvider,
  } as OfferFilesProviders;
}

export async function connectBrowserContract(
  wallet: ContractWallet,
  config: MidnightBrowserConfig,
): Promise<ConnectedOfferFilesContract> {
  // midnight-js reads a module-global network id; must be set before any
  // wallet/contract/serialization call or the ledger throws.
  console.log(`[browserContract] setNetworkId("${config.networkId}")`);
  setNetworkId(config.networkId as any);

  console.log(`[browserContract] connect: building providers (${wallet.label})…`);
  const providers = await buildProviders(wallet, config);

  console.log('[browserContract] connect: compiling OfferFilesContract client…');
  const compiledContract = CompiledContract.make(
    'contract-offer-files',
    OfferFilesContract.Contract as any,
  ).pipe(
    // offer-files.compact declares no `witness`, so the generated
    // `Witnesses<PS>` type is `{}` — there is nothing to bind.
    CompiledContract.withWitnesses({} as never),
    // Browser fetches ZK assets via FetchZkConfigProvider; this path is a
    // placeholder satisfying the API (counter.ts uses './' the same way).
    CompiledContract.withCompiledFileAssets('./'),
  );

  console.log(`[browserContract] connect: findDeployedContract ${config.contractAddress}`);
  const contract = (await findDeployedContract(providers, {
    contractAddress: config.contractAddress,
    compiledContract: compiledContract as any,
    privateStateId: OFFER_FILES_PRIVATE_STATE_ID,
    initialPrivateState: {},
  })) as FoundOfferFilesContract;

  console.log('[browserContract] connect: ready');
  return { contract, providers, compiledContract, config };
}

/**
 * Shielded-only path: maker tx has no Intent slots and asset deltas live in
 * segment 0's guaranteed Zswap offer. `balanceSealedTransaction` can't be
 * used here — it walks `tx.intents` and throws "No segments found in the
 * provided transaction" when the map is empty. Mirror the taker side via
 * `makeIntent` and merge: segment-0 offers compose because they aren't
 * keyed Intents.
 *
 * Unshielded offers are dispatched away from this function in
 * `proveAndSubmitOffers` because Lace's unshielded `makeIntent` adds an
 * empty structural Intent[1] to *both* maker and taker txs, which collides
 * on merge with "key (segment_id) collision during intents merge: 1".
 */
async function balanceShieldedViaMirrorMerge(
  connectedApi: ConnectedAPI,
  makerTx: any,
  swap: { segId: number; imbalances: Map<any, bigint> },
): Promise<{ balancedHex: string; txHash: string }> {
  dlog('mirror+merge: enter', { segId: swap.segId });
  const { shieldedAddress } = await timed('mirror+merge: wallet.getShieldedAddresses()', () =>
    connectedApi.getShieldedAddresses(),
  );
  const { unshieldedAddress } = await timed('mirror+merge: wallet.getUnshieldedAddress()', () =>
    connectedApi.getUnshieldedAddress(),
  );
  dlog('mirror+merge: taker addresses', {
    shieldedAddress: `${shieldedAddress.slice(0, 20)}…`,
    unshieldedAddress: `${unshieldedAddress.slice(0, 20)}…`,
  });

  type DesiredInput = { kind: 'shielded' | 'unshielded'; type: string; value: bigint };
  type DesiredOutput = DesiredInput & { recipient: string };
  const takerInputs: DesiredInput[] = [];
  const takerOutputs: DesiredOutput[] = [];

  // +N for token T → maker spent N, taker should receive N (taker output).
  // -N for token T → maker outputs N, taker should provide N (taker input).
  for (const [tt, delta] of swap.imbalances) {
    const tag = (tt as any).tag as 'shielded' | 'unshielded' | 'dust';
    if (tag === 'dust') continue; // batcher pays
    if (tag !== 'shielded' && tag !== 'unshielded') continue;
    const type = (tt as any).raw as string;
    if (delta > 0n) {
      takerOutputs.push({
        kind: tag,
        type,
        value: delta,
        recipient: tag === 'shielded' ? shieldedAddress : unshieldedAddress,
      });
    } else if (delta < 0n) {
      takerInputs.push({ kind: tag, type, value: -delta });
    }
  }

  const makerIntentIds: number[] = makerTx.intents
    ? Array.from(makerTx.intents.keys() as Iterable<number>)
    : [];

  // Shielded `makeIntent` doesn't populate an Intent slot, so the requested
  // id is moot — the resulting taker tx will have intents.size === 0
  // regardless. Pass a non-1 value defensively in case Lace ever changes
  // shielded `makeIntent` to add a structural Intent[1].
  const requestedTakerIntentId: number | 'random' = 1000;

  console.log('[browserContract] complete (mirror+merge): taker mirror', {
    segId: swap.segId,
    makerIntentIds,
    requestedTakerIntentId,
    inputs: takerInputs.map(i => ({ ...i, value: i.value.toString() })),
    outputs: takerOutputs.map(o => ({ ...o, value: o.value.toString() })),
  });

  // ⬇ THE reported hang lands here: this is a call into the Lace wallet to build
  // the taker's intent. If it never resolves you'll see the `▶ wallet.makeIntent`
  // line below with no matching `✓` — the wallet is stuck (pending popup, coin
  // selection, or indexer sync), NOT the backend.
  dlog('mirror+merge: → calling wallet.makeIntent', {
    takerInputs: takerInputs.map((i) => ({ ...i, value: i.value.toString() })),
    takerOutputs: takerOutputs.map((o) => ({ ...o, value: o.value.toString() })),
    intentId: requestedTakerIntentId,
    payFees: false,
  });
  const { tx: takerTxHex } = await timed(
    'mirror+merge: wallet.makeIntent(taker inputs/outputs) ← COMMON HANG POINT',
    () =>
      connectedApi.makeIntent(takerInputs, takerOutputs, {
        intentId: requestedTakerIntentId,
        payFees: false,
      }),
  );
  console.log('[browserContract] complete (mirror+merge): taker tx hex bytes', takerTxHex.length / 2);

  const takerTx = LedgerV8Transaction.deserialize(
    'signature',
    'proof',
    'binding',
    fromHex(takerTxHex),
  );

  // Full taker tx shape (mirror of the maker tx segment log earlier in
  // proveAndSubmitOffers). Tells us which segIds Lace actually populated and
  // what's in each segment — enough to diagnose any "intents merge: N"
  // collision or zswap-offer composition error.
  const takerIntentIds: number[] = takerTx.intents
    ? Array.from(takerTx.intents.keys() as Iterable<number>)
    : [];
  const takerFallibleIds: number[] = takerTx.fallibleOffer
    ? Array.from(takerTx.fallibleOffer.keys() as Iterable<number>)
    : [];
  console.log('[browserContract] complete (mirror+merge): taker tx shape', {
    requestedTakerIntentId,
    actualTakerIntentIds: takerIntentIds,
    actualTakerFallibleIds: takerFallibleIds,
    segmentImbalances: Object.fromEntries(
      Array.from(new Set<number>([0, ...takerIntentIds, ...takerFallibleIds])).map((segId) => {
        try {
          const imb = takerTx.imbalances(segId) as Map<any, bigint>;
          return [
            segId,
            Array.from(imb.entries()).map(([tt, v]) => ({
              tag: (tt as any).tag,
              raw: (tt as any).raw,
              delta: v.toString(),
            })),
          ];
        } catch {
          return [segId, 'imbalances() threw'];
        }
      }),
    ),
  });

  // Sanity check: under the shielded-only dispatch, neither maker nor taker
  // should have any Intent slots, so `overlapping` is expected to be empty.
  // A non-empty list here means the dispatch in `proveAndSubmitOffers` is
  // mis-routing an offer that has Intents into mirror+merge.
  const overlap = makerIntentIds.filter((id) => takerIntentIds.includes(id));
  console.log('[browserContract] complete (mirror+merge): about to merge', {
    makerIntentIds,
    takerIntentIds,
    overlapping: overlap,
    expectsCollision: overlap.length > 0,
  });

  dlog('mirror+merge: → makerTx.merge(takerTx) (ledger, sync)');
  const merged = makerTx.merge(takerTx);
  dlog('mirror+merge: ✓ merged (ledger)');
  const balancedHex = toHex(merged.serialize());
  const txHash = (merged as any).transactionHash?.() ?? '';
  const mergedIntentIds: number[] = (merged as any).intents
    ? Array.from((merged as any).intents.keys() as Iterable<number>)
    : [];
  console.log('[browserContract] complete (mirror+merge): merged maker + taker', {
    bytes: balancedHex.length / 2,
    txHash,
    mergedIntentIds,
  });
  return { balancedHex, txHash };
}

/**
 * Sealed-balance path: maker tx has at least one Intent slot. Hand the
 * sealed tx to Lace's `balanceSealedTransaction(payFees: false)` — Lace
 * adds the counterparty side, the batcher pays fees in DUST.
 *
 * Reached for unshielded4unshielded (segment-0 deltas + empty Intent[1])
 * and any future numbered-Intent offers. Mirror+merge can't be used here
 * because Lace's unshielded `makeIntent` would put a colliding Intent[1]
 * on the taker side; sealed-balance has no such issue because it doesn't
 * go through `makeIntent` on the taker side.
 */
async function balanceMixedViaSealedBalance(
  connectedApi: ConnectedAPI,
  makerTxHex: string,
): Promise<{ balancedHex: string; txHash: string }> {
  dlog('sealed balance: → calling wallet.balanceSealedTransaction', {
    makerTxBytes: makerTxHex.length / 2,
    payFees: false,
  });
  const { tx: balancedHex } = await timed(
    'sealed balance: wallet.balanceSealedTransaction(payFees:false) ← possible hang point',
    () => connectedApi.balanceSealedTransaction(makerTxHex, { payFees: false }),
  );
  let txHash = '';
  try {
    const balancedTx = LedgerV8Transaction.deserialize(
      'signature',
      'proof',
      'binding',
      fromHex(balancedHex),
    );
    txHash = (balancedTx as any).transactionHash?.() ?? '';
  } catch {
    // Hash is best-effort for logging; missing it shouldn't block submission.
  }
  console.log('[browserContract] complete (sealed balance): returned', {
    bytes: balancedHex.length / 2,
    txHash,
  });
  return { balancedHex, txHash };
}

/**
 * Complete one or more makers' bech32m offer blobs as the connected browser
 * wallet, in a SINGLE transaction.
 *
 * The N maker halves are decoded and folded together first (see
 * services/offerBatch.ts), and the wallet then balances the merged result once.
 * Settling a ladder offer-by-offer re-spent the taker's only coin — nothing
 * told the wallet about take #k's spend before take #k+1 was balanced, and the
 * node rejected everything after the first with
 * `Zswap(NullifierAlreadyPresent)`. One balancing pass, one submission, no
 * window.
 *
 * A merged shielded↔shielded ladder is the same SHAPE as one shielded offer as
 * far as this function's dispatch is concerned — no Intents, deltas summed in
 * segment 0 — so it takes the same mirror+merge route, and the mirrored taker
 * side covers the ladder's totals. `offerBatch.test.ts` asserts that against
 * the real ledger. Offers that cannot compose (two unshielded legs both at
 * segment 1) are refused by `mergeMakerOffersToBytes` before anything is sent.
 *
 * N=1 is byte-for-byte the old single-offer path: the wallet is handed the
 * blob's own decoded bytes, not a re-serialization of them.
 *
 * Two balancing strategies, dispatched on the merged maker tx's shape:
 *   - segment-0 deltas, no Intent slots (shielded-only) → mirror+merge
 *   - any Intent slot present (unshielded or numbered)  → balanceSealedTransaction
 *
 * Neither strategy works for both cases:
 *   - `balanceSealedTransaction` throws "No segments found in the provided
 *     transaction" on shielded-only offers (it walks `tx.intents`, which is
 *     empty there).
 *   - mirror+merge collides with "key (segment_id) collision during intents
 *     merge: 1" on unshielded offers — Lace's unshielded `makeIntent` always
 *     lands its Intent at segId 1, so maker and taker would both carry it.
 */
export async function proveAndSubmitOffers(
  connectedApi: ConnectedAPI,
  config: MidnightBrowserConfig,
  offerBech32ms: string[],
): Promise<{ txHash: string }> {
  dlog('proveAndSubmitOffers: enter', {
    networkId: config.networkId,
    contractAddress: config.contractAddress,
    proofServerUri: config.proofServerUri,
    offers: offerBech32ms.length,
    offerLens: offerBech32ms.map((b) => b.length),
  });
  setNetworkId(config.networkId as NetworkId);

  console.log('[browserContract] complete: decoding offer bytes');
  dlog('proveAndSubmitOffers: → decode + merge maker txs (sync)');
  const decoded = decodeMakerOffers(offerBech32ms, config.networkId as NetworkId);
  const { tx: makerTx, bytes: makerBytes } = mergeMakerOffersToBytes(decoded);
  dlog('proveAndSubmitOffers: ✓ maker txs deserialized + merged', {
    offers: decoded.length,
    bytes: decoded.map((d) => d.raw.length),
    mergedBytes: makerBytes.length,
  });

  // Diagnostic: full segment shape of the (merged) maker tx. Drives the
  // dispatch decision below (Intent slot present? → sealed balance; else →
  // mirror+merge) and gives fast triage on any balance/merge error.
  const intentIds: number[] = makerTx.intents
    ? (Array.from(makerTx.intents.keys()) as number[])
    : [];
  const fallibleIds: number[] = makerTx.fallibleOffer
    ? (Array.from(makerTx.fallibleOffer.keys()) as number[])
    : [];
  console.log('[browserContract] complete: maker tx segments', {
    offers: decoded.length,
    intentIds,
    fallibleIds,
    segmentImbalances: Object.fromEntries(
      Array.from(new Set<number>([0, ...intentIds, ...fallibleIds])).map((segId) => {
        try {
          const imb = makerTx.imbalances(segId) as Map<any, bigint>;
          return [
            segId,
            Array.from(imb.entries()).map(([tt, v]) => ({
              tag: (tt as any).tag,
              raw: (tt as any).raw,
              delta: v.toString(),
            })),
          ];
        } catch {
          return [segId, 'imbalances() threw'];
        }
      }),
    ),
  });

  const { useMirrorMerge, ...swap } = chooseLaceBalancing(makerTx);
  const strategy = useMirrorMerge
    ? 'mirror+merge (segment 0 / guaranteed offer)'
    : 'balanceSealedTransaction (numbered Intent)';
  console.log('[browserContract] complete: chose strategy', {
    segId: swap.segId,
    strategy,
  });

  let balancedHex: string;
  let txHash: string;
  try {
    if (useMirrorMerge) {
      ({ balancedHex, txHash } = await timed('balance via mirror+merge', () =>
        balanceShieldedViaMirrorMerge(connectedApi, makerTx, swap),
      ));
    } else {
      ({ balancedHex, txHash } = await timed('balance via sealed-balance', () =>
        balanceMixedViaSealedBalance(connectedApi, toHex(makerBytes)),
      ));
    }
    dlog('proveAndSubmitOffers: ✓ balanced', { strategy, balancedBytes: balancedHex.length / 2, txHash });
  } catch (e: any) {
    console.error('[browserContract] complete: balancing failed', {
      strategy,
      offers: decoded.length,
      name: e?.name,
      message: e?.message,
      raw: e,
    });
    throw new Error(
      `Wallet failed to balance the maker offer: ${e?.message ?? e?.name ?? 'unknown'}`,
      { cause: e },
    );
  }

  const coinPublicKeyHex = parseCoinPublicKeyToHex(
    (await timed('proveAndSubmitOffers: wallet.getShieldedAddresses() (for batcher addr)', () =>
      connectedApi.getShieldedAddresses(),
    )).shieldedCoinPublicKey,
    config.networkId as NetworkId,
  );

  console.log('[browserContract] complete: submitting to batcher', {
    txHash,
    offers: decoded.length,
  });
  try {
    await timed('proveAndSubmitOffers: submitToBatcher (one submission for the whole batch)', () =>
      submitToBatcher(balancedHex, 'finalized', coinPublicKeyHex),
    );
  } catch (e: any) {
    console.error('[browserContract] complete: batcher submit failed', {
      message: e?.message,
      raw: e,
    });
    throw new Error(
      `Batcher submit failed: ${e?.message ?? JSON.stringify(e) ?? 'unknown'}`,
      { cause: e },
    );
  }

  console.log('[browserContract] complete: done', { txHash, offers: decoded.length });
  return { txHash };
}

/**
 * Single-offer take — the degenerate N=1 of {@link proveAndSubmitOffers}, so
 * both paths decode, balance and submit through exactly the same code.
 */
export function proveAndSubmitOffer(
  connectedApi: ConnectedAPI,
  config: MidnightBrowserConfig,
  offerBech32m: string,
): Promise<{ txHash: string }> {
  return proveAndSubmitOffers(connectedApi, config, [offerBech32m]);
}
