// The compiled bridge contract and the metadata the engine needs to drive it.
//
// `contract-bridge/src/managed/` is generated by scripts/compile.sh (gitignored,
// as in every Midnight template): run `bun run compile` in this package first.
// The generated module imports `@midnight-ntwrk/compact-runtime-0.20` (pinned by
// scripts/pin-contract-runtime.mjs); everything else in the template keeps the
// engine's compact-runtime 0.18.
import { readFileSync } from "node:fs";
import * as path from "node:path";
import { ContractState as ContractState020 } from "@midnight-ntwrk/compact-runtime-0.20";
import * as Bridge from "./contract-bridge/src/managed/contract/index.js";

/** Name `deployMidnightContract` and `MidnightAdapter` know the contract by. */
export const CONTRACT_NAME = "contract-bridge";
export const PACKAGE_DIR = import.meta.dirname!;
/** `deployMidnightContract`'s `baseDir`: it looks for `<baseDir>/contract-bridge/src/managed`. */
export const CONTRACTS_BASE_DIR = PACKAGE_DIR;
/** midnight-js zk config path (keys, zkir, compiler/). */
export const MANAGED_DIR = path.join(PACKAGE_DIR, CONTRACT_NAME, "src", "managed");

export { Bridge };
export const BridgeContract = Bridge.Contract;
export const bridgeLedger = Bridge.ledger;
export const bridgePureCircuits = Bridge.pureCircuits;
export type BridgeLedger = Bridge.Ledger;

/**
 * `ContractState` from the contract's OWN runtime (the 0.20 alias). The sync's
 * `Midnight:Generic` primitive must decode through
 * `midnightLedgerFromTxStateHex(bridgeLedger, BridgeContractState)`: the plain
 * `ledger` path throws `expected instance of ChargedState`, because the sync's
 * onchain-runtime alias is a separate module instance (00050 P0 S2).
 */
export const BridgeContractState = ContractState020;

/** The contract's own runtime (0.20 alias), for local circuit execution in tests and tools. */
export * as BridgeRuntime from "@midnight-ntwrk/compact-runtime-0.20";

// ── contract-info.json ──────────────────────────────────────────────────────

export interface TypeDefinition {
  "type-name": string;
  maxval?: string | number;
  length?: number;
  name?: string;
  elements?: { name: string; type: TypeDefinition }[];
  types?: TypeDefinition[];
}
export interface ContractInfo {
  circuits: {
    name: string;
    pure: boolean;
    arguments: { name: string; type: TypeDefinition }[];
    "result-type": TypeDefinition;
  }[];
  witnesses: unknown[];
  contracts: unknown[];
}

/**
 * `managed/compiler/contract-info.json`, as compactc wrote it. The relayer's
 * `MidnightAdapter` takes it as is: since engine E8 the batcher's argument
 * parser understands 0.35.0's `Curve25519Point` (`{x, y}`, each < 2^255 - 19)
 * and `Curve25519Scalar` (< L), the types of `mintFromSolana`'s
 * `sig: Ed25519Signature` (questions-file Q16).
 */
export function readContractInfo(managedDir: string = MANAGED_DIR): ContractInfo {
  return JSON.parse(
    readFileSync(path.join(managedDir, "compiler", "contract-info.json"), "utf8"),
  ) as ContractInfo;
}
