// The compiled bridge contract and the metadata the engine needs to drive it.
//
// `contract-bridge/src/managed/` is generated by scripts/compile.sh (gitignored,
// as in every Midnight template): run `bun run compile` in this package first.
// The generated module imports `@midnight-ntwrk/compact-runtime-0.20` (pinned by
// scripts/pin-contract-runtime.mjs); everything else in the template keeps the
// engine's compact-runtime 0.18.
import { readFileSync } from "node:fs";
import * as path from "node:path";
import { ContractState as ContractState020 } from "@midnight-ntwrk/compact-runtime-0.20";
import * as Bridge from "./contract-bridge/src/managed/contract/index.js";

/** Name `deployMidnightContract` and `MidnightAdapter` know the contract by. */
export const CONTRACT_NAME = "contract-bridge";
export const PACKAGE_DIR = import.meta.dirname!;
/** `deployMidnightContract`'s `baseDir`: it looks for `<baseDir>/contract-bridge/src/managed`. */
export const CONTRACTS_BASE_DIR = PACKAGE_DIR;
/** midnight-js zk config path (keys, zkir, compiler/). */
export const MANAGED_DIR = path.join(PACKAGE_DIR, CONTRACT_NAME, "src", "managed");

export { Bridge };
export const BridgeContract = Bridge.Contract;
export const bridgeLedger = Bridge.ledger;
export const bridgePureCircuits = Bridge.pureCircuits;
export type BridgeLedger = Bridge.Ledger;

/**
 * `ContractState` from the contract's OWN runtime (the 0.20 alias). The sync's
 * `Midnight:Generic` primitive must decode through
 * `midnightLedgerFromTxStateHex(bridgeLedger, BridgeContractState)`: the plain
 * `ledger` path throws `expected instance of ChargedState`, because the sync's
 * onchain-runtime alias is a separate module instance (00050 P0 S2).
 */
export const BridgeContractState = ContractState020;

/** The contract's own runtime (0.20 alias), for local circuit execution in tests and tools. */
export * as BridgeRuntime from "@midnight-ntwrk/compact-runtime-0.20";

// ── contract-info.json ──────────────────────────────────────────────────────

export interface TypeDefinition {
  "type-name": string;
  maxval?: string | number;
  length?: number;
  name?: string;
  elements?: { name: string; type: TypeDefinition }[];
  types?: TypeDefinition[];
}
export interface ContractInfo {
  circuits: {
    name: string;
    pure: boolean;
    arguments: { name: string; type: TypeDefinition }[];
    "result-type": TypeDefinition;
  }[];
  witnesses: unknown[];
  contracts: unknown[];
}

/** `managed/compiler/contract-info.json`, as compactc wrote it. */
export function readContractInfo(managedDir: string = MANAGED_DIR): ContractInfo {
  return JSON.parse(
    readFileSync(path.join(managedDir, "compiler", "contract-info.json"), "utf8"),
  ) as ContractInfo;
}

/** Curve25519 base field modulus p = 2^255 - 19 (point coordinates are < p). */
const CURVE25519_P = (1n << 255n) - 19n;
/** Ed25519 group order L (scalars are < L). */
const ED25519_L = (1n << 252n) + 27742317777372353535851937790883648493n;

/**
 * Rewrites the two compactc 0.35.0 type names the batcher's argument parser
 * does not know into shapes it does:
 *   Curve25519Point  → Struct { x: Uint, y: Uint }   (the runtime value is `{x, y}` bigints)
 *   Curve25519Scalar → Uint                          (the runtime value is a bigint)
 *
 * WHY: `MidnightAdapter` validates and parses every circuit argument through
 * `parseCircuitArgs(contractInfo)`, which supports Uint/Bytes/Boolean/Opaque/
 * Struct/Tuple only and throws `Unsupported type: Curve25519Point` for the
 * `sig: Ed25519Signature` argument of `mintFromSolana`. The contract info is a
 * constructor argument of the adapter, so the template hands it this
 * translated copy; the parsed values are exactly what the circuit takes. The
 * engine-side fix (teach the parser these types) is questions-file Q16.
 */
export function batcherContractInfo(info: ContractInfo = readContractInfo()): ContractInfo {
  const translate = (t: TypeDefinition): TypeDefinition => {
    switch (t["type-name"]) {
      case "Curve25519Point":
        return {
          "type-name": "Struct",
          name: "Curve25519Point",
          elements: [
            { name: "x", type: { "type-name": "Uint", maxval: (CURVE25519_P - 1n).toString() } },
            { name: "y", type: { "type-name": "Uint", maxval: (CURVE25519_P - 1n).toString() } },
          ],
        };
      case "Curve25519Scalar":
        return { "type-name": "Uint", maxval: (ED25519_L - 1n).toString() };
      default:
        return {
          ...t,
          ...(t.elements
            ? { elements: t.elements.map((e) => ({ name: e.name, type: translate(e.type) })) }
            : {}),
          ...(t.types ? { types: t.types.map(translate) } : {}),
        };
    }
  };
  return {
    ...info,
    circuits: info.circuits.map((c) => ({
      ...c,
      arguments: c.arguments.map((a) => ({ name: a.name, type: translate(a.type) })),
      "result-type": translate(c["result-type"]),
    })),
  };
}
