// The Passport account key-set pin (plan 00058 Interfaces D-4): the circuits a Night Market account
// carries, each with the SHA-256 of its deployed verifier key, the key-set fingerprint and the
// passport commit. Generated by scripts/pin-from-night-market.ts; never edited by hand.
import fs from "node:fs";
import path from "node:path";

export type PassportPin = {
  source: { repo: string; commit: string; file: string; sha256: string };
  keySet: string;
  passportCommit: string;
  accountSourceSha256: string;
  circuits: Record<string, string>;
};

export const DEFAULT_PIN_PATH = path.resolve(import.meta.dirname!, "pin/passport-account.pin.json");

export function loadPin(file: string = DEFAULT_PIN_PATH): PassportPin {
  const pin = JSON.parse(fs.readFileSync(file, "utf8")) as PassportPin;
  const hex = (n: number) => new RegExp(`^[0-9a-f]{${n}}$`);
  if (!hex(64).test(pin.keySet) || !hex(40).test(pin.passportCommit) || !hex(64).test(pin.accountSourceSha256)) {
    throw new Error(`${file} is not a Passport pin (keySet, passportCommit, accountSourceSha256)`);
  }
  const entries = Object.entries(pin.circuits ?? {});
  if (entries.length === 0 || !entries.every(([, d]) => hex(64).test(d))) throw new Error(`${file} has no valid circuits`);
  if (!pin.circuits.deposit_shielded) throw new Error(`${file} does not pin deposit_shielded`);
  return pin;
}

/** "passport-ed25519@<first 8 hex of the key set>" (I-3 (a) `delivery.adapter`). */
export const adapterIdFor = (pin: PassportPin) => `passport-ed25519@${pin.keySet.slice(0, 8)}`;
