import { Type } from "@sinclair/typebox";
import { type GrammarDefinition, mapPrimitivesToGrammar } from "@paima/concise";
import { localhostConfig } from "./config.ts";

export const grammar = {
  schedule: [
    ["tick", Type.Integer()],
    [
      "type",
      Type.Union([
        Type.Literal("block"),
        Type.Literal("timestamp"),
      ]),
    ],
    ["message", Type.String()],
  ],
  attack: [
    ["playerId", Type.Integer()],
    ["moveId", Type.Integer()],
  ],
  throw_error: [],
  // TODO: How do we get this from the known payload types?
  //       This is a ERC20 transfer.
  transfer: [
    [
      "payload",
      Type.Object({
        to: Type.String(),
        from: Type.String(),
        value: Type.String(),
      }),
    ],
  ],
  switchMap: [["mapId", Type.String()]],
  // Midnight contract state with proper EncodedStateValue schema
  midnightContractState: [
    [
      "payload",
      Type.Recursive((Self) =>
        Type.Union([
          Type.Object({
            tag: Type.Literal("null"),
          }),
          Type.Object({
            tag: Type.Literal("cell"),
            content: Self,
          }),
          Type.Object({
            tag: Type.Literal("array"),
            content: Type.Array(Self),
          }),
          Type.Object({
            tag: Type.Literal("map"),
            content: Type.Array(Type.Tuple([Type.Any(), Self])), // Map as [key, value] pairs
          }),
        ])
      ),
    ],
  ],
  // Auto-generate other primitives, but exclude midnight (we define it explicitly above)
  ...(() => {
    const autoGenerated = mapPrimitivesToGrammar(localhostConfig.primitives);
    const { midnightContractState, ...otherPrimitives } = autoGenerated;
    return otherPrimitives;
  })(),
} as const satisfies GrammarDefinition;

// const foo = mapPrimitivesToGrammar(localhostConfig.primitives);
// localhostConfig.primitives.TransferEvent;
