# Avail Light Client config (no --network needed)

# Logging
log_level = "info"

# API server
http_server_host = "127.0.0.1"
http_server_port = 7007

# RPC to full node (custom 9955)
full_node_ws = ["ws://127.0.0.1:9955"]

# App / LC behavior
app_id = 0
confidence = 92.0
avail_path = "avail_path"
network_mode = "both"  # both | p2p-only | rpc-only

# LibP2P
port = 37000
webrtc_port = 37001
# secret_key = { seed = "avail" }  # optional deterministic key
bootstraps = ["/ip4/127.0.0.1/tcp/39000/p2p/12D3KooWMm1c4pzeLPGkkCJMAgFbsfQ8xmVDusg272icWsaNHWzN"]

# Telemetry / network identity (equivalent to local --network defaults)
ot_collector_endpoint = "http://127.0.0.1:4317"
genesis_hash = "DEV"