// `src/remappings/assets.ts` inlines the remappings .txt files as base64. It
// was regenerated by hand and drifted: the bundle kept emitting `@paima/`
// remappings long after the .txt sources moved to `@effectstream/`, so
// `remappings-hardhat` wrote a remappings.txt whose `@effectstream` substitution
// never matched. Regenerate with `bun run assets:generate` from the repo root.

import { test, expect } from "bun:test";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

import bundle from "../src/remappings/assets.ts";

const PACKAGE_ROOT = resolve(import.meta.dir, "..");

// Paths in this config are relative to the package root, not to the config.
const config: { files: { importPath: string; calledName: string }[] } =
  JSON.parse(
    readFileSync(
      resolve(PACKAGE_ROOT, "src/remappings/assets-config.json"),
      "utf8",
    ),
  );

test("every configured remapping file is present in the bundle", () => {
  expect(Object.keys(bundle.files).sort()).toEqual(
    config.files.map((f) => f.calledName).sort(),
  );
});

for (const file of config.files) {
  test(`bundled ${file.calledName} matches ${file.importPath}`, () => {
    const source = readFileSync(resolve(PACKAGE_ROOT, file.importPath), "utf8");
    const bundled = new TextDecoder().decode(
      bundle.files[file.calledName as keyof typeof bundle.files].content,
    );
    expect(bundled).toBe(source);
  });
}
