// AUTO-GENERATED by scripts/generate-assets.ts - DO NOT EDIT BY HAND.
// Source list: packages/chains/evm-hardhat/src/remappings/assets-config.json
// Regenerate with: bun run assets:generate

function decodeBase64(b64: string): Uint8Array {
  return Uint8Array.from(atob(b64), (c) => c.charCodeAt(0));
}

const bundledObject = {
  files: {
    "remappings.hardhat": {
      content: decodeBase64("QG9wZW56ZXBwZWxpbi89bm9kZV9tb2R1bGVzL0BvcGVuemVwcGVsaW4vCkBlZmZlY3RzdHJlYW0vPW5vZGVfbW9kdWxlcy9AZWZmZWN0c3RyZWFtLwo="),
      extension: "txt",
    },
    "remappings.forge": {
      content: decodeBase64("QG9wZW56ZXBwZWxpbi89Li4vLi4vLi4vLi4vbm9kZV9tb2R1bGVzL0BvcGVuemVwcGVsaW4vCkBlZmZlY3RzdHJlYW0vPS4uLy4uLy4uLy4uL25vZGVfbW9kdWxlcy9AZWZmZWN0c3RyZWFtLwo="),
      extension: "txt",
    },
  },
};

export default bundledObject;
