#!/usr/bin/env bun
/**
 * Generates the `assets.ts` bundles that inline file contents (SQL migrations,
 * Solidity remappings) as base64 so they survive being published to npm and
 * imported from a bundled/browser build.
 *
 * Replaces `deno run jsr:@codemonument/asset-builder`, which we can no longer
 * run: current versions emit a file importing `jsr:@std/encoding`, which Bun
 * cannot resolve. Because of that the bundles were being hand-patched, and both
 * of them silently went stale (the db bundle kept a `CREATE EXTENSION pg_ivm`
 * that had been deleted from the .sql source, and the evm-hardhat bundle still
 * held `@paima/` remappings). `--check` exists so CI catches that next time.
 *
 *   bun run assets:generate   # rewrite every bundle
 *   bun run assets:check      # fail if a bundle is out of date
 */

import { readFileSync, writeFileSync } from "node:fs";
import { extname, resolve } from "node:path";

const REPO_ROOT = resolve(import.meta.dir, "..");

interface AssetsConfig {
  files: { importPath: string; calledName: string }[];
}

interface Bundle {
  /** Label used in log output. */
  name: string;
  /** `assets-config.json` describing what goes into the bundle. */
  config: string;
  /**
   * Directory the config's `importPath` entries are relative to. Not always the
   * config's own directory: evm-hardhat's config lives in `src/remappings/` but
   * its paths are relative to the package root.
   */
  base: string;
  /** Generated file to write. */
  out: string;
}

const BUNDLES: Bundle[] = [
  {
    name: "@effectstream/db migrations",
    config: "packages/node-sdk/db/assets-config.json",
    base: "packages/node-sdk/db",
    out: "packages/node-sdk/db/migrations/assets.ts",
  },
  {
    name: "@effectstream/evm-hardhat remappings",
    config: "packages/chains/evm-hardhat/src/remappings/assets-config.json",
    base: "packages/chains/evm-hardhat",
    out: "packages/chains/evm-hardhat/src/remappings/assets.ts",
  },
];

/**
 * `atob` rather than `node:buffer`, so the generated module stays usable in the
 * browser bundle of @effectstream/frontend-sdk.
 */
const PREAMBLE = `function decodeBase64(b64: string): Uint8Array {
  return Uint8Array.from(atob(b64), (c) => c.charCodeAt(0));
}
`;

export function renderBundle(bundle: Bundle): string {
  const config: AssetsConfig = JSON.parse(
    readFileSync(resolve(REPO_ROOT, bundle.config), "utf8"),
  );

  const entries = config.files.map((file) => {
    const path = resolve(REPO_ROOT, bundle.base, file.importPath);
    const content = readFileSync(path).toString("base64");
    const extension = extname(file.importPath).replace(/^\./, "");
    return [
      `    ${JSON.stringify(file.calledName)}: {`,
      `      content: decodeBase64(${JSON.stringify(content)}),`,
      `      extension: ${JSON.stringify(extension)},`,
      `    },`,
    ].join("\n");
  });

  return [
    `// AUTO-GENERATED by scripts/generate-assets.ts - DO NOT EDIT BY HAND.`,
    `// Source list: ${bundle.config}`,
    `// Regenerate with: bun run assets:generate`,
    ``,
    PREAMBLE,
    `const bundledObject = {`,
    `  files: {`,
    ...entries,
    `  },`,
    `};`,
    ``,
    `export default bundledObject;`,
    ``,
  ].join("\n");
}

function readIfExists(path: string): string | undefined {
  try {
    return readFileSync(path, "utf8");
  } catch {
    return undefined;
  }
}

function main(): void {
  const check = process.argv.includes("--check");
  const stale: string[] = [];

  for (const bundle of BUNDLES) {
    const outPath = resolve(REPO_ROOT, bundle.out);
    const expected = renderBundle(bundle);
    const actual = readIfExists(outPath);

    if (check) {
      if (actual === expected) {
        console.log(`  ok      ${bundle.out}`);
      } else {
        stale.push(bundle.out);
        console.error(
          `  STALE   ${bundle.out}${actual === undefined ? " (missing)" : ""}`,
        );
      }
      continue;
    }

    if (actual === expected) {
      console.log(`  unchanged  ${bundle.out}`);
    } else {
      writeFileSync(outPath, expected);
      console.log(`  wrote      ${bundle.out}  (${bundle.name})`);
    }
  }

  if (stale.length > 0) {
    console.error(
      `\n${stale.length} asset bundle(s) out of sync with their sources.\n` +
        `Run \`bun run assets:generate\` and commit the result.`,
    );
    process.exit(1);
  }
}

if (import.meta.main) {
  main();
}
